const Route = {
  TEMP_TEST_SCREEN: 'TEMP_TEST_SCREEN',

  SPLASH_SCREEN: 'SPLASH_SCREEN',

  TAB_STACK: 'TAB_STACK',
  MAIN_STACK: 'MAIN_STACK',

  HOME_SCREEN: 'HOME_SCREEN',
  NOTE_SCREEN: 'NOTE_SCREEN',
  TASK_SCREEN: 'TASK_SCREEN',

  TASK_CREATE_SCREEN: 'TASK_CREATE_SCREEN',
  TASK_EDIT_SCREEN: 'TASK_EDIT_SCREEN',
  CREATE_AND_EDIT_NOTE_SCREEN: 'CREATE_AND_EDIT_NOTE_SCREEN',

  BOTTOM_FONT_STYLE_SELECTION_MODAL: 'BOTTOM_FONT_STYLE_SELECTION_MODAL',
};

export default Route;
