const Route = {
  TEMP_TEST_SCREEN: 'TEMP_TEST_SCREEN',

  TAB_STACK: 'TAB_STACK',
  MAIN_STACK: 'MAIN_STACK',

  HOME_SCREEN: 'HOME_SCREEN',
  NOTE_SCREEN: 'NOTE_SCREEN',
  TASK_SCREEN: 'TASK_SCREEN',

  TASK_CREATE_SCREEN: 'TASK_CREATE_SCREEN',
};

export default Route;
